name: Build and Upload ZIP to GitHub Repository

on:
  workflow_dispatch: # 手动触发

jobs:
  build_and_upload_job:
    runs-on: ubuntu-latest
    name: Build and Upload ZIP Job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies and Build
        run: |
          bun install
          bun run build:azure
          cp staticwebapp.config.json ./dist

      - name: Dump DEV_DB_NAME
          run: echo -n "${{ secrets.DEV_DB_NAME }}" | xxd -ps