name: Build and Push to GitHub Repository

on:
  workflow_dispatch: # 手动触发

jobs:
  build_and_push_job:
    runs-on: ubuntu-latest
    name: Build and Push Job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies and Build
        run: |
          bun install
          bun run build:azure
          cp staticwebapp.config.json ./dist

      - name: Checkout Target Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/MJL-baby-keyboard/via-app target-repo
          rm -rf target-repo/*
          cp -r ./dist/* target-repo/

      - name: Commit and Push Changes
        run: |
          cd target-repo
          git add .
          git commit -m "Deploy: Update static files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
