name: Deploy to GitHub Repository

on:
  workflow_dispatch: # 手动触发工作流
  repository_dispatch:
    types: [definition_update]

jobs:
  build_and_push_job:
    runs-on: ubuntu-latest
    name: Build and Push Job
    steps:
      # 克隆当前仓库
      - uses: actions/checkout@v3
        with:
          submodules: true

      # 设置 Bun 环境
      - name: Use Bun
        uses: oven-sh/setup-bun@v1

      # 安装依赖并构建
      - name: bun install, and build
        run: |
          bun install
          bun run build:azure
          cp staticwebapp.config.json ./dist

      # 克隆目标仓库
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: MJL-baby-keyboard/via-app # 目标仓库地址
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token
          ref: main # 检出目标仓库的默认分支

      # 同步生成的文件到目标仓库
      - name: Sync generated files
        run: |
          rm -rf *
          cp -r ../dist/* .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated files from CI/CD [skip ci]" || echo "No changes to commit"
      
      # 推送更改到目标仓库
      - name: Push changes
        run: |
          git push origin main
