name: Build and Push to GitHub Repository

on:
  workflow_dispatch: # 改为手动触发工作流

jobs:
  build_and_push_job:
    runs-on: ubuntu-latest
    name: Build and Push Job
    steps:
      # Step 1: 检出当前代码
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      # Step 2: 设置 Bun 运行环境
      - name: Use Bun
        uses: oven-sh/setup-bun@v1

      # Step 3: 安装依赖并构建项目
      - name: Install Dependencies and Build
        run: |
          bun install
          bun run build:azure
          cp staticwebapp.config.json ./dist

      # Step 4: 检出目标仓库
      - name: Checkout Target Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone https://github.com/MJL-baby-keyboard/via-app target-repo
          rm -rf target-repo/* # 删除旧文件
          cp -r ./dist/* target-repo/ # 复制新文件
        env:
          TARGET_REPO: https://github.com/MJL-baby-keyboard/via-app # 替换为您的目标仓库

      # Step 5: 提交更改并推送
      - name: Commit and Push Changes
        run: |
          cd target-repo
          git add .
          git commit -m "Deploy: Update static files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
